import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
export const metadata = {
  title: "Jardin Miralibres",
  description: "Generated by Matias Gigena",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
